[id='downloading-beta-installation-images_{context}']

= 下载安装 ISO 映像

在开始安装 {rel8} 之前，必须下载一个安装 ISO 映像。映像可从 {ProductName} 网站获取。网站提供以下基本类型的介质：

DVD1 ISO::
该映像包含安装程序以及在交互式安装过程中可以安装的所有软件包的集合。有时也称为“二进制 DVD ”或“二进制 ISO 映像”。对于大多数用户，建议下载此文件。

Boot ISO::
只包含安装程序，而不包含任何可安装的软件包。此映像将允许您启动安装，但您必须xref:standard-install:assembly_preparing-for-your-installation.adoc#prepare-installation-source_preparing-for-your-installation[准备一个软件包源]并在xref:standard-install:assembly_graphical-installation.adoc#configuring-installation-source_configuring-software-settings[包选择界面]中输入其 URL，使用xref:standard-install:assembly_custom-boot-options.adoc#installation-source-boot-options_custom-boot-options[引导选项]或使用xref:advanced-install:assembly_kickstart-commands-and-options-reference.adoc#repo_kickstart-commands-for-system-configuration[ Kickstart 命令]才能完成安装。

可选，您可以在下载完成后使用 checksum 程序（如 [application]*sha256sum*）来验证映像文件的完整性。所有下载均附带其校验和，以供参考：

[literal,subs="+quotes,attributes,verbatim,macros"]
....
$ sha256sum {ProductName}-8-x86_64-dvd.iso
`85a...46c  {ProductName}-8-x86_64-dvd.iso`
....

类似的工具可用于 link:++http://www.labtestproject.com/files/win/sha256sum/sha256sum.exe++[Microsoft Windows] 和 link:++https://itunes.apple.com/us/app/hashtab/id517065482++[Mac OS X]。您也可以在引导命令行上使用 `rd.live.check` 选项。有关详细信息，请参见xref:standard-install:assembly_booting-installer.adoc#editing-boot-options_booting-the-installer[编辑引导选项]。

从官方网站下载 ISO 映像文件后，您可以：

* 按照xref:standard-install:assembly_preparing-for-your-installation.adoc#making-an-installation-cd-or-dvd_preparing-for-your-installation[创建可引导 DVD 或 CD]中的说明将其刻录到 CD 或 DVD。

* 使用它创建一个可引导的 USB 驱动器；请参阅xref:standard-install:assembly_preparing-for-your-installation.adoc#create-bootable-usb-linux_preparing-for-your-installation[在 Linux 上创建可引导 USB 设备]、xref:standard-install:assembly_preparing-for-your-installation.adoc#creating-a-bootable-usb-windows_preparing-for-your-installation[在 Windows 上创建可引导 USB 设备]和xref:standard-install:assembly_preparing-for-your-installation.adoc#creating-a-bootable-usb-mac_preparing-for-your-installation[在 Mac OS X 上创建可引导 USB 设备]。

* 将其放在本地硬盘驱动器或网络位置上，以用作安装源。有关具体说明，请参阅xref:standard-install:assembly_preparing-for-your-installation.adoc#prepare-installation-source_preparing-for-your-installation[准备安装源]。

* 使用它来准备 _预引导执行环境_ （PXE）服务器，该服务器使您可以通过网络引导安装系统。有关说明，请参阅xref:advanced-install:assembly_preparing-for-a-network-install.adoc[使用 PXE 从网络准备安装]。
