[id="installation-source-boot-options_{context}"]
= 安装源引导选项

本部分包含有关各种安装源引导选项的信息。

inst.repo=::
`inst.repo=` 引导选项指定安装源，即提供软件包仓库的位置和描述这些仓库的有效 `.treeinfo` 文件。例如：`inst.repo=cdrom`。
`inst.repo=` 选项的目标必须是以下安装介质之一：

* 安装树，其目录结构包含该安装程序映像、软件包和仓库数据以及可用的`.treeinfo` 文件。
* DVD（系统 DVD 驱动器中的物理磁盘）。
* 完整 {rel8} 安装 DVD 的ISO映像，保存在硬盘中或者安装系统可以访问的网络位置。
+
您可以使用 `inst.repo=` 引导选项使用不同的格式配置不同的安装方法。下表包含 `inst.repo=` 引导选项语法的详细信息：
+
.inst.repo= 安装源引导选项
[options="header",cols="1,3,2"]
|===
| 源类型  | 引导选项格式 | 源格式
| CD/DVD 驱动器  | `inst.repo=cdrom&#91;:__device__&#93;` | 将DVD安装为物理磁盘。 footnote:[如果遗漏了 __device__ ，安装程序会自动搜索包含安装 DVD 的驱动器。]
| 安装树 | `inst.repo=hd:__device__:__/path__` | 安装DVD的映像文件或安装树，它是安装 DVD 上目录和文件的完整副本。
| NFS 服务器  | `inst.repo=nfs:&#91;__options__:&#93;__server__:__/path__` | 安装 DVD 的映像文件。 footnote:[NFS 服务器选项默认使用 NFS 协议版本 3。要使用其他版本 X，请在  __options__ 中添加 `+nfsvers=__X__`。]
| HTTP 服务器 | `inst.repo=http://__host/path__` .3+| 安装树，它是安装 DVD 上目录和文件的完整副本。
| HTTPS 服务器 | `inst.repo=https://__host/path__`
| FTP 服务器 | `inst.repo=ftp://__username__:__password__@__host__/__path__`
| HMC  | `inst.repo=hmc` |
|===
+

您可以使用以下格式设置磁盘设备名称：

* 内核设备名称，例如： `/dev/sda1` or `sdb2`
* 文件系统标签，例如： `LABEL=Flash` 或 `LABEL=CENTOS8`
* 文件系统 UUID，例如： `UUID=8176c7bf-04ff-403a-a832-9557f94e61db`
+
非字母数字字符必须以 `\xNN` 形式显示，其中 _NN_ 是使用十六进制代表的字符。例如：`\x20` 为空格`(" ")`。

inst.addrepo=::
使用 `inst.addrepo=` 引导选项添加一个附加的仓库，该仓库可以与主仓库(`inst.repo=`)一起用作另一个安装源。您可以在一次引导期间多次使用 `inst.addrepo=` 引导选项。下表包含 `inst.addrepo=` 引导选项语法的详细信息。
+
[NOTE]
====
`REPO_NAME` 是仓库的名称，在安装过程中是必需的。这些仓库仅在安装过程中使用。它们未安装在已安装的系统上。
====
+
.inst.addrepo 安装源引导选项
[options="header"]
|===
| 安装源  | 引导选项格式 | 附加信息
| URL 上的可安装树  | `inst.addrepo=REPO_NAME,[http,https,ftp]://<host>/<path>` | 在给定的URL中查找可安装树。
| NFS 路径上的可安装树   | `inst.addrepo=REPO_NAME,nfs://<server>:/<path>` | 在给定的 NFS 路径中查找可安装树。主机后面需要冒号。安装程序将 `nfs://` 之后的所有内容直接传递给 mount 命令，而不是根据 RFC 2224 解析 URL。
| 安装环境中的可安装树 | `inst.addrepo=REPO_NAME,file://<path>` | 在安装环境中的给定位置查找可安装树。要使用此选项，在安装程序尝试加载可用软件组之前，必须先挂载仓库。此选项的好处是，您可以在一个可引导的 ISO 上拥有多个仓库，并且可以从 ISO 安装主仓库和附加仓库。附加仓库的路径是 `/run/install/source/REPO_ISO_PATH`。另外，您可以在 Kickstart 文件的 `%pre` 部分中挂载仓库目录。路径必须是绝对路径并以 `/` 开头，例如 `inst.addrepo=REPO_NAME,file:///<path>`
| 硬盘驱动器  | `inst.addrepo=REPO_NAME,hd:<device>:<path>` | 挂载给定的 _<device>_ 分区，并从 _<path>_ 指定的 ISO 安装。如果未指定 _<path>_，则安装程序将在 _<device>_ 上查找有效的安装 ISO。此安装方法需要具有有效可安装树的 ISO。
|===
+

inst.noverifyssl=::
`noverifyssl=` 引导选项阻止安装程序验证除附加 Kickstart 仓库之外的所有 HTTPS 连接的 SSL 证书，其中-`--noverifyssl` 可以针对每个仓库进行设置。


inst.stage2=::

使用 `inst.stage2=` 引导选项指定安装程序运行时映像的位置。此选项需要指向包含有效 `.treeinfo` 文件的目录的路径。运行时映像的位置从 `.treeinfo` 文件中读取。如果 `.treeinfo` 文件不可用，安装程序会尝试从 `LiveOS/squashfs.img` 加载映像。
+
如果未指定 `inst.stage2` 选项，安装程序将尝试使用 `inst.repo` 选项指定的位置。
+
您应该仅为 PXE 引导指定此选项。安装 DVD 和 Boot ISO 已包含正确的 `inst.stage2` 选项，可从其自身引导安装程序。
+
[NOTE]
====
默认情况下， `inst.stage2=` 引导选项在安装介质上使用，并设置为特定标签，例如`inst.stage2=hd:LABEL={ProductName}-{ProductNumber}-BaseOS-x86_64`。如果您修改包含运行时映像的文件系统的默认标签，或者使用自定义过程来引导安装系统，则必须验证 `inst.stage2=` 选项设置为正确的值。
====

inst.stage2.all::
`inst.stage2.all` 引导选项用于指定多个 HTTP、HTTPS 或 FTP 源。您可以将  `inst.stage2=` 引导选项与 `inst.stage2.all` 选项一起使用多次，以从源顺序获取映像，直到成功为止。 例如：
+
[subs="macros"]
----
inst.stage2.all
inst.stage2=http://hostname1/path_to_install_tree/
inst.stage2=http://hostname2/path_to_install_tree/
inst.stage2=http://hostname3/path_to_install_tree/
----


inst.dd=::
`inst.dd=` 引导选项用于在安装过程中执行驱动程序更新。有关在安装过程中如何更新驱动程序的信息，请参阅xref:advanced-install:index.adoc[_高级安装_]文档。

inst.repo=hmc::
从 DVD1 引导时，安装程序会提示您输入其他内核参数。要将 DVD 设置为安装源，请将 `inst.repo=hmc` 附加到内核参数中。然后，安装程序将启用 `SE` 和 `HMC` 文件访问，从 DVD 中获取 stage2 的映像，并提供对 DVD 上软件包的访问以进行软件选择。此选项消除了对外部网络设置的需求，并扩展了安装选项。

inst.proxy::
当从 HTTP、HTTPS、FTP 源执行安装时，使用 `inst.proxy` 引导选项。例如：
+
[subs="macros"]
----
[PROTOCOL://][USERNAME[:PASSWORD]@]HOST[:PORT]
----

inst.nosave::
使用 `inst.nosave` 选项控制是否将安装日志和相关文件保存到安装的系统中，例如输入 `input_ks`、 `output_ks`、`all_ks`、`logs` 和 `all`。多个值可以组合为逗号分隔的列表，例如：`input_ks,logs`。
+
[NOTE]
====
`inst.nosave` 选项用于从已安装的系统中排除 Kickstart %post 脚本无法删除的文件，例如日志和输入/输出 Kickstart 结果。
====
+
.inst.nosave 引导选项
[options="header"]
|===
| 选项  | 描述
| input_ks  | 禁用保存输入 Kickstart 结果的功能。
| output_ks | 禁用保存由安装程序生成的输出 Kickstart 结果的功能。
| all_ks | 禁用保存输入和输出 Kickstart 结果的功能。
| logs  | 禁用保存所有安装日志的功能。
| all | 禁用保存所有 Kickstart 结果和所有日志的功能。
|===

inst.multilib::
使用 `inst.multilib` 引导选项将 DNF 的 `multilib_policy` 设置为 *all*，而不是 *best*。

memcheck::
`memcheck` 引导选项执行检查以验证系统是否有足够的 RAM 来完成安装。如果没有足够的 RAM，则会停止安装过程。系统检查是粗略的，安装期间的内存使用情况取决于软件包的选择，用户界面（例如图形或文本）以及其他参数。

nomemcheck::
`nomemcheck` 引导选项不执行检查以验证系统是否有足够的 RAM 来完成安装。不支持使用小于建议的最小内存量执行安装的任何尝试，这可能会导致安装过程失败。
