[id="debug-boot-options_{context}"]
= 调试引导选项

本部分包含有关调试问题时可以使用的选项的信息。

inst.rescue=::
使用 `inst.rescue=` 选项来运行救援环境。该选项对于尝试诊断和修复系统非常有用。

inst.updates=::
使用 `inst.updates=` 选项指定要在安装期间应用的 `updates.img` 文件的位置。更新源有很多。
+
.inst.updates= 源更新
[options="header"]
|===
| 源  | 描述 | 示例
| 来自网络的更新 | 使用 `inst.updates=` 的最简单方法是指定 `updates.img` 的网络位置。这不需要对安装树进行任何修改。要使用此方法，请编辑内核命令行以包含 `inst.updates`。 | `inst.updates=http://some.website.com/path/to/updates.img`。
| 来自磁盘映像的更新 | 将 `updates.img` 保存在软盘驱动器或 USB 闪存盘上。这只能使用 `ext2` 文件系统类型的 `updates.img`来完成。要将映像的内容保存在软盘驱动器中，请插入软盘并运行命令。 | `dd if=updates.img of=/dev/fd0 bs=72k count=20`。要使用 USB 闪存盘或闪存介质，请将 `/dev/fd0` 替换为您的 USB 闪存盘的设备名称。
| 来自安装树的更新 | 如果使用 CD、硬盘、HTTP 或 FTP 安装，则可以将`updates.img` 保存在安装树中，以便所有安装都可以检测到 .img 文件。将文件保存在 `images/` 目录中。文件名必须为 `updates.img`。 | 对于 NFS 安装，有两个选项：可以将映像保存在 `images/` 目录中，也可以保存在安装树的 `RHupdates/` 目录中。
|===

inst.loglevel=::
使用 `inst.loglevel=` 选项指定记录在终端上的最低消息级别。这只涉及终端日志记录；日志文件始终包含所有级别的消息。此选项从最低级别到最高级别的可能值为： `debug`、 `info`、 `warning`、 `error` 和 `critical`。默认值为 `info`，这意味着在默认情况下，日志记录终端显示的消息范围从 `info` 到 `critical`。

inst.syslog=::
安装开始时， `inst.syslog=` 选项会将日志消息发送到指定主机上的 `syslog` 进程。远程 `syslog` 进程必须配置为接受传入连接。

inst.virtiolog=::
使用 `inst.virtiolog=` 选项指定要用于转发日志的 virtio 端口(位于 `/dev/virtio-ports/name` 的字符设备)。默认值为 `org.fedoraproject.anaconda.log.0`；如果存在此端口，则使用该端口。

inst.zram::
`inst.zram` 选项控制安装期间 zRAM 交换的使用。该选件在系统 RAM 内创建压缩块设备，并将其用于交换空间，而不是硬盘驱动器。这使得安装程序运行时使用的可用内存比没有压缩时要少，而且还可能使安装速度更快。默认情况下，在 RAM 不超过 2 GiB 的系统上启用 zRAM 交换，在内存超过 2 GiB 的系统上禁用 zRAM 交换。您可以使用此选项更改此行为；在内存超过 2 GiB 的系统上，使用 `inst.zram=1` 启用该功能；在内存为 2 GiB 或更少的系统上，使用 `inst.zram=0` 禁用该功能。

rd.live.ram::
如果指定了`rd.live.ram` 选项，则 `stage 2` 映像将复制到 RAM 中。当 `stage 2` 映像位于 NFS 服务器上时，使用此选项可将映像大小所需的最小内存增加约 500 MiB。

inst.nokill::
`inst.nokill` 选项是一个调试选项，用于在发生致命错误或安装过程结束时阻止安装程序重新启动。使用 `inst.nokill` 选项捕获重新启动时丢失的安装日志。

inst.noshell::
如果在安装过程中不想在终端会话 2（tty2）上使用 shell，请使用 `inst.noshell` 选项。

inst.notmux::
如果不想在安装期间使用 tmux，请使用 `inst.notmux` 选项。生成的输出没有终端控制字符，用于非交互用途。

remotelog::
使用 `remotelog` 选项通过 TCP 连接将所有日志发送到远程 `host:port`。如果没有监听程序，连接将失效，安装将照常进行。
