[id="network-boot-options_{context}"]
= 网络引导选项

本部分包含有关常用网络引导选项的信息。

[NOTE]
====
初始网络初始化由 `dracut` 处理。有关完整列表，请参阅  `dracut.cmdline(7)` 手册页。
====


ip=::
使用 `ip=` 引导选项配置一个或多个网络接口。要配置多个接口，可以多次使用 `ip` 选项，每个接口一次；要执行此操作，必须使用 `rd.neednet=1` 选项，并且必须使用 `bootdev` 选项指定主引导接口。或者，您可以使用一次 `ip` 选项，然后使用 Kickstart 设置更多接口。此选项接受几种不同的格式。下表包含有关最常见选项的信息。
+
[NOTE]
====
在下表中：

* `ip` 参数指定客户端IP地址。您可以在方括号中指定 IPv6 地址，例如 [2001:DB8::1]。
* `gateway` 参数是默认网关。也接受IPv6地址。
* `netmask` 参数是要使用的网络掩码。它可以是完整的网络掩码（例如255.255.255.0）或前缀（例如 64）。
* `hostname` 参数是客户端系统的主机名。此参数是可选的。
====
+
.网络接口配置引导选项格式
[options="header"]
|===
| 配置方法  | 引导选项格式
| 自动配置任何接口   | `ip=method`
| 自动配置特定接口   | `ip=interface:method`
| 静态配置  | `ip=ip::gateway:netmask:hostname:interface:none`
| 使用覆盖自动配置特定接口 | `ip=ip::gateway:netmask:hostname:interface:method:mtu`
|===
+
[NOTE]
====
使用覆盖自动配置特定接口的 method 使用自动配置的特定 method（例如dhcp）调出接口，但是覆盖自动获取的 IP 地址、网关、网络掩码、主机名或其他指定参数。所有参数都是可选的，因此仅指定要覆盖的参数。
====
+
`method` 参数可以是以下任意一个：
+
.自动接口配置方法
[options="header"]
|===
| 自动配置 method  | 值
| DHCP    | `dhcp`
| IPv6 DHCP    | `dhcp6`
| IPv6 自动配置  | `auto6`
| iSCSI 引导固件表 (iBFT)  | `ibft`
|===
+
[NOTE]
====
* 如果您使用需要网络访问权限的引导选项（例如 `inst.ks=http://host:/path`），而未指定 ip 选项，则安装程序将使用 `ip=dhcp`。
* 要自动连接到 iSCSI 目标，必须激活网络设备才能访问该目标。建议的激活网络的方法是使用 `ip=ibft` 引导选项。
====

nameserver=::
`nameserver=` 选项指定名称服务器的地址。您可以多次使用此选项。

bootdev=::
`bootdev=` 选项指定引导接口。如果您使用多个 ip 选项，则此选项是必需的。

ifname=::
`ifname=` 选项将接口名称分配给具有给定 MAC 地址的网络设备。您可以多次使用此选项。语法为 `ifname=interface:MAC`。例如：
+
[subs="macros"]
----
ifname=eth0:01:23:45:67:89:ab
----
+
[NOTE]
====
`ifname=` 选项是在安装过程中设置自定义网络接口名称的唯一受支持的方法。
====

inst.dhcpclass=::
`inst.dhcpclass=` 选项指定 DHCP 供应商类别标识符。`dhcpd` 服务将该值视为供应商类别标识符。默认值为 `anaconda-$(uname -srm)`。

inst.waitfornet=::
使用 `inst.waitfornet=SECONDS` 引导选项会使安装系统在安装前等待网络连接。`SECONDS` 参数中给出的值指定在超时并继续安装过程(即使网络连接不存在)之前等待网络连接的最长时间。

