[id="creating-a-bootable-usb-windows_{context}"]
= 在 Windows 上创建可引导 USB 设备

按照以下步骤在 Windows 系统上创建可引导 USB 设备。根据工具的不同，过程会有所不同。{OrgName} 建议使用 Fedora Media Writer，该软件可从 https://github.com/FedoraQt/MediaWriter/releases 下载。

[NOTE]
====
Fedora Media Writer 是 Fedora 社区产品，{OrgName} 不支持它。您可以在以下位置报告该工具的任何问题：https://github.com/FedoraQt/MediaWriter/issues.
====

[discrete]
== 前提

* 您已下载了安装 ISO 映像，如xref:standard-install:assembly_preparing-for-your-installation.adoc#downloading-beta-installation-images_preparing-for-your-installation[下载安装 ISO 映像]中所述。
* *DVD1* ISO 映像大于 4.7 GB，因此您必须有足够大的 USB 闪存驱动器来保存 ISO 映像。


[discrete]
== 步骤

[NOTE]
====
此过程具有破坏性，USB 闪存驱动器上的数据会在没有警告的情况下被销毁。
====

. 从 https://github.com/FedoraQt/MediaWriter/releases 下载并安装 Fedora Media Writer。
+
[NOTE]
====
MediaWriter.要在 {productname} 上安装 Fedora Media Writer，请使用预构建的 Flatpak 软件包。您可以从官方 Flatpak 仓库 Flathub.org处获取该软件包，网址为 https://flathub.org/apps/details/org.fedoraproject.MediaWriter。
====

. 将 USB 闪存驱动器连接到系统。
. 打开 Fedora Media Writer。
. 在主窗口中，单击 *自定义映像*，然后选择之前下载的 {productname} ISO映像。
. 在 *写入自定义映像* 窗口中，选择要使用的驱动器。
. 单击 *写入磁盘* 。引导介质创建过程开始。在操作完成之前，不要拔下驱动器的插头。此操作可能需要几分钟，具体取决于 ISO 映像的大小和 USB 驱动器的写入速度。
. 操作完成后，卸载USB驱动器。USB驱动器现在可以用作引导设备。
