[id="creating-an-installation-source_{context}"]
= 在 NFS 服务器上创建安装源

按照以下步骤将安装源放在 NFS 服务器上。使用此安装方法可以从单个源安装多个系统，而无需连接到物理介质。

[discrete]
== 前提

* 您具有使用 {rel8} 的服务器的管理员级别访问权限，并且该服务器与要安装的系统位于同一网络上。
* 您已下载了 DVD 1 ISO 映像。有关详细信息，请参阅xref:standard-install:assembly_preparing-for-your-installation.adoc#downloading-beta-installation-images_preparing-for-your-installation[下载安装 ISO 映像]。
* 您已经从映像文件创建了可引导 CD、DVD 或 USB 设备。有关详细信息，请参阅xref:standard-install:assembly_preparing-for-your-installation.adoc#making-media_preparing-for-your-installation[创建安装介质]。
* 您已验证防火墙是否允许正在安装的系统访问远程安装源。

[discrete]
== 步骤

. 安装 [package]`nfs-utils` 软件包：
+
[subs="quotes, macros, attributes"]
----
# yum install nfs-utils
----

. 将 DVD1 ISO 映像复制到 NFS 服务器上的目录。

. 使用文本编辑器打开 [filename]`/etc/exports` 文件，并使用以下语法添加一行：
+
[subs="quotes, macros, attributes"]
----
/__exported_directory__/ __clients__
----

. 将 _/exported_directory/_ 替换为包含 ISO 映像目录的完整路径。将 __clients__ 替换为目标系统的主机名或 IP 地址、所有目标系统可用于访问 ISO 映像的子网，或者，如果要允许对 NFS 服务器具有网络访问权限的任何系统使用ISO映像，请使用星号(*)。有关此字段格式的详细信息，请参见 `exports(5)` 手册页。
+
使 `/circleos8-install/` 目录对所有客户端都是只读的基本配置是：
+
[subs="quotes, macros, attributes"]
----
/circleos8-install *
----

. 保存 [filename]`/etc/exports` 文件并退出文本编辑器。
. 启动 nfs 服务：
+
[subs="quotes, macros, attributes"]
----
# systemctl start nfs-server.service
----
+
如果在更改 [filename]`/etc/exports` 文件之前服务正在运行，请对正在运行的 NFS 服务器运行以下命令以重新加载其配置：
+
[subs="quotes, macros, attributes"]
----
# systemctl reload nfs-server.service
----
+
现在可以通过 NFS 访问 ISO 映像，并且可以将其用作安装源。

[NOTE]
====
在配置安装源时，请使用 `nfs:` 作为协议、服务器主机名或 IP 地址、冒号 `(:)` 和保存 ISO 映像的目录。例如，如果服务器主机名为 `myserver.example.com`，并且您已将 ISO 映像保存在 `/circleos8-install/` 中，请指定 `nfs:myserver.example.com:/circleos8-install/` 作为安装源。
====
