[id="creating-a-bootable-usb-mac_{context}"]
= 在 Mac OS X 上创建可引导 USB 设备

按照以下步骤在 Mac OS X 系统上创建可引导 USB 设备。

[discrete]
== 前提

* 您已下载了安装 ISO 映像，如xref:standard-install:assembly_preparing-for-your-installation.adoc#downloading-beta-installation-images_preparing-for-your-installation[下载安装 ISO 映像]中所述。
* *DVD1* ISO 映像大于 4.7 GB，因此您必须有足够大的 USB 闪存驱动器来保存 ISO 映像。


[discrete]
== 步骤

[NOTE]
====
此过程具有破坏性，USB 闪存驱动器上的数据会在没有警告的情况下被销毁。
====

. 将 USB 闪存驱动器连接到系统。

. 使用 [command]`diskutil list` 命令确认设备路径。设备路径的格式为 _/dev/disknumber_ ，其中 number 是磁盘的编号。磁盘从零（0）开始编号。通常，磁盘0是 OS X 恢复磁盘，磁盘 1 是主要的 OS X 安装。在以下示例中，USB 设备是 `disk2`：
+
[subs="quotes, macros, attributes"]
----
$ diskutil list
/dev/disk0
#:                       TYPE NAME                    SIZE       IDENTIFIER
0:      GUID_partition_scheme                        *500.3 GB   disk0
1:                        EFI EFI                     209.7 MB   disk0s1
2:          Apple_CoreStorage                         400.0 GB   disk0s2
3:                 Apple_Boot Recovery HD             650.0 MB   disk0s3
4:          Apple_CoreStorage                         98.8 GB    disk0s4
5:                 Apple_Boot Recovery HD             650.0 MB   disk0s5
/dev/disk1
#:                       TYPE NAME                    SIZE       IDENTIFIER
0:                  Apple_HFS YosemiteHD             *399.6 GB   disk1
Logical Volume on disk0s1
8A142795-8036-48DF-9FC5-84506DFBB7B2
Unlocked Encrypted
/dev/disk2
#:                       TYPE NAME                    SIZE       IDENTIFIER
0:     FDisk_partition_scheme                        *8.0 GB     disk2
1:               Windows_NTFS SanDisk USB             8.0 GB     disk2s1
----


. 要识别您的 USB 闪存驱动器，请将 NAME、TYPE 和 SIZE 列与您的闪存驱动器进行比较。例如，NAME 应该是 *Finder* 工具中闪存驱动器图标的标题。您还可以将这些值与闪存驱动器信息面板中的值进行比较。

. 使用 [command]`diskutil unmountDisk` 命令卸载闪存驱动器的文件系统卷：
+
[subs="quotes, macros, attributes"]
----
$ diskutil unmountDisk /dev/disknumber
Unmount of all volumes on disknumber was successful
----
+
命令完成后，闪存驱动器的图标将从桌面上消失。如果图标没有消失，则可能选择了错误的磁盘。尝试卸载系统磁盘时意外返回 *无法卸载* 错误。

. 以 root 用户登录：
+
[subs="quotes, macros, attributes"]
----
$ su -
----

. 出现提示时输入 root 密码。

. 使用 [command]`dd` 命令作为 sudo 命令的参数，将 ISO 映像写入闪存驱动器：
+
[subs="quotes, macros, attributes"]
----
# sudo dd if=/path/to/image.iso of=/dev/rdisknumber bs=1m>
----
+
[NOTE]
====
Mac OS X 为每个存储设备都提供了块（/dev/disk*）和字符设备（/dev/rdisk*）文件。将映像写入 /dev/rdisknumber 字符设备比写入 /dev/disknumber 块设备快。
====

. 要将 _/Users/user_name/Downloads/{ProductName}-8-x86_64-boot.iso_ 文件写入 _/dev/rdisk2_ 设备，请运行以下命令：
+
[subs="quotes, macros, attributes"]
----
# sudo dd if=/Users/user_name/Downloads/{ProductName}-8-x86_64-boot.iso of=/dev/rdisk2
----

. 等待 `dd` 命令完成将映像写入设备的操作。出现 *#* 提示时，数据传输完成。显示提示时，请注销 root 帐户并拔下 USB 驱动器。现在可以将 USB 驱动器用作引导设备了。
