[id="starting-manual-partitioning_{context}"]
= 启动手动分区

.前提

* 当前显示 *安装信息摘要* 界面。
* 所有磁盘都可用于安装程序。

.步骤

. 选择用于安装的磁盘：

.. 单击 *安装目的地* 以打开 *安装目的地* 窗口。

.. 通过单击相应的图标选择安装所需的磁盘。选定的磁盘上带有选中标记。

.. 在 `存储配置` 下，选择 `自定义` 单选按钮。

.. 可选：要启用 LUK存储加密，请选中 `加密我的数据` 复选框。

.. 单击 *完成*。


. 如果选择对存储进行加密，将打开一个用于输入磁盘加密口令的对话框。输入 LUKS 口令：

.. 在两个文本字段中输入口令。要切换键盘布局，请使用键盘图标。
+
WARNING: 在用于输入密码的对话框中，您无法更改键盘布局。选择英语键盘布局以在安装程序中输入密码。

.. 单击 *保存口令*。将打开 *手动分区* 窗口。

. 已删除的挂载点列在左侧窗格中。挂载点由检测到的操作系统安装组织。因此，如果在多个安装之间共享一个分区，则某些文件系统可能会显示多次。

.. 在左窗格中选择挂载点；可自定义的选项显示在右窗格中。
+
[NOTE]
====
* 如果您的系统包含现有文件系统，请确保有足够的空间用于安装。要删除任何分区，请在列表中选择它们，然后单击 *-* 按钮。
+
该对话框有一个复选框，您可以使用该复选框删除被删除分区所属的系统使用的所有其他分区。

* 如果没有现有分区，并且您要创建推荐的一组分区作为起点，请从左窗格中选择首选的分区方案（{productname} 默认是 LVM），然后单击 [GUI]`单击此处自动创建它们` 链接。
+
将创建与可用存储大小成比例的 `/boot`、`/` （root）卷和交换卷，并在左窗格中列出。这些是典型安装的推荐文件系统，但您可以添加其他文件系统和挂载点。
====

.. 单击 *完成* 以确认所有更改，并返回到 *安装摘信息要* 窗口。

继续xref:assembly_graphical-installation.adoc#adding-a-mount-point_manual-partitioning[添加挂载点]、xref:assembly_graphical-installation.adoc#configuring-a-mount-point-file-system_manual-partitioning[配置各个挂载点] 和 xref:assembly_graphical-installation.adoc#customizing-a-partition-or-volume_manual-partitioning[配置基础分区或卷]。
