[id="boot-loader-installation_{context}"]
= 配置引导加载程序

//TODO: This needs to be reworked to a concept and task modules

{ProductName} 使用 GRand Unified Bootloader version 2（[application]*GRUB2*）作为引导加载程序。

引导加载程序是系统启动时运行的第一个程序，负责加载并将控制转移到操作系统。[application]*GRUB2* 可以引导任何兼容的操作系统(包括 Microsoft Windows)，还可以使用链式加载将控制权转移到不支持的操作系统的其他引导加载程序。

[WARNING]
====
安装 [application]*GRUB2* 可能会覆盖现有的引导加载程序。
====

如果已经安装了操作系统，{ProductName} 安装程序会尝试自动检测并配置引导加载程序以启动另一个操作系统。如果未检测到引导加载程序，则可以在完成安装后手动配置任何其他操作系统。
//TODO: link to GRUB2 config docs for more details

如果要将  {ProductName}  安装在多个磁盘上，可能需要手动指定要安装引导加载程序的磁盘。

.步骤

. 在 *安装目的地* 窗口中，单击 *完整磁盘摘要以及引导程序* 链接。将打开 *所选磁盘* 对话框。
+
引导加载程序已安装在您选择的设备或 UEFI 系统上；在引导分区期间，将在目标设备上创建 *EFI 系统分区*。

. 更改引导设备，请从列表中选择一个设备，然后单击 *设置为引导设备*。您只能将一个设备设置为引导设备。

. 要禁用新的引导加载程序安装，请选择当前标记为要引导的设备，然后单击 *不安装引导加载程序*。这可确保 [application]*GRUB2* 未安装在任何设备上。

[WARNING]
====
如果选择不安装引导加载程序，则不能直接引导系统，必须使用其他引导方法，例如独立的商用引导加载应用程序。仅当您有其他方式引导系统时才使用此选项。
====

引导加载程序可能还需要创建特殊分区，具体取决于您的系统使用的是 BIOS 还是 UEFI 固件，或者引导驱动器是否具有GUID分区表（GPT）或主引导记录（MBR，也称为 `msdos`）标签。如果使用自动分区，安装程序将创建分区。
//TODO: Add link to recommended partitioning scheme.
