[id="configuring-a-tftp-server-for-uefi-based-clients_{context}"]
= 为基于 UEFI 的客户端配置 TFTP 服务器

以下步骤介绍如何为基于 UEFI 的 AMD64、Intel 64 和 64 位 ARM 系统配置 TFTP 服务器和 DHCP 服务器，并在 PXE 服务器上启动 TFTP 服务。


[discrete]
== 步骤

. 以 root 身份安装 `tftp-server` 软件包：
+
[subs="macros"]
----
# yum install tftp-server
----

. 允许防火墙中 `tftp service` 的传入连接：
+
[subs="macros"]
----
# firewall-cmd --add-service=tftp
----
+
[NOTE]
====
此命令在下次重新启动服务器之前启用临时访问。要启用永久访问，请将 `--permanent` 选项添加到命令中。
====

. 将您的 DHCP 服务器配置为使用 *shim* 打包的引导映像。`/etc/dhcp/dhcpd.conf` 文件中的示例配置可能如下所示：
+
[subs="quotes, macros, attributes"]
----
option space pxelinux;
option pxelinux.magic code 208 = string;
option pxelinux.configfile code 209 = text;
option pxelinux.pathprefix code 210 = text;
option pxelinux.reboottime code 211 = unsigned integer 32;
option architecture-type code 93 = unsigned integer 16;

subnet 10.0.0.0 netmask 255.255.255.0 {
	option routers 10.0.0.254;
	range 10.0.0.2 10.0.0.253;

	class "pxeclients" {
	  match if substring (option vendor-class-identifier, 0, 9) = "PXEClient";
	  next-server 10.0.0.1;

	  if option architecture-type = 00:07 {
	    filename "shim.efi";
	  } else {
	    filename "pxelinux/pxelinux.0";
		}
  }
}
----

. 从 `shim` 包访问 `shim.efi` 文件，从 DVD1 ISO 映像文件中的 `grub2-efi` 包访问 `grubx64.efi` 文件：
+
[subs="macros"]
----
# mount -t iso9660 /path_to_image/name_of_image.iso /mount_point -o loop,ro
----
+
[subs="macros"]
----
# cp -pr /mount_point/BaseOS/Packages/shim-version-architecture.rpm /publicly_available_directory
----
+
[subs="macros"]
----
# cp -pr /mount_point/BaseOS/Packages/grub2-efi-version-architecture.rpm /publicly_available_directory
----
+
[subs="macros"]
----
# umount /mount_point
----

. 解压软件包：
+
[subs="macros"]
----
# rpm2cpio shim-version-architecture.rpm | cpio -dimv
----
+
[subs="macros"]
----
# rpm2cpio grub2-efi-version-architecture.rpm | cpio -dimv
----

. 从您的引导目录复制 EFI 引导映像。
+
[subs="macros"]
----
# cp publicly_available_directory/boot/efi/EFI/redhat/shimx64.efi /var/lib/tftpboot/uefi/
----
+
[subs="macros"]
----
# cp publicly_available_directory/boot/efi/EFI/redhat/grubx64.efi /var/lib/tftpboot/uefi
----
+
[IMPORTANT]
====
复制 `shimx64.efi` 文件后，必须将其重命名为 `shim.efi` 。
====

. 将名为 `grub.cfg` 的配置文件添加到 `tftpboot/` 目录。位于`/var/lib/tftpboot/uefi/grub.cfg` 的示例配置文件可能如下所示：
+
[subs="quotes, macros, attributes"]
----
set timeout=60
menuentry '{rel8}' {
  linuxefi images/{ProductName}-{ProductNumber}/vmlinuz ip=dhcp inst.repo=http://10.32.5.1/{ProductName}-{ProductNumber}/x86_64/iso-contents-root/
  initrdefi images/{ProductName}-{ProductNumber}/initrd.img
}
----
+
[NOTE]
====
 * 如果没有其运行时映像，安装程序将无法启动。使用 `inst.stage2` 引导选项指定映像的位置。或者，您可以使用 `inst.repo=` 选项指定映像和安装源。
 * 用于 `inst.repo` 的安装源位置必须包含有效的 `.treeinfo` 文件。
 * 选择 {rel8} 安装 DVD 作为安装源时，`.treeinfo` 文件指向 BaseOS 和 AppStream 仓库。您可以使用单个 `inst.repo` 选项加载两个仓库。
====

. 创建子目录以将引导镜像文件存储在 `/var/lib/tftpboot/` 目录中，并将引导镜像文件复制到该目录。在本例中，使用目录 `/var/lib/tftpboot/images/{ProductName}-{ProductNumber}/`：
+
[subs="quotes, macros, attributes"]
----
# mkdir -p /var/lib/tftpboot/images/{ProductName}-{ProductNumber}/
# cp /path_to_x86_64_images/pxeboot/{vmlinuz,initrd.img} /var/lib/tftpboot/images/{ProductName}-{ProductNumber}/
----

. 启动并启用 `dhcpd` 服务：
+
[subs="macros"]
----
# systemctl start dhcpd
# systemctl enable dhcpd
----

. 启动并启用管理 `tftp` 服务的 `xinetd` 服务：
+
[subs="macros"]
----
# systemctl start xinetd
# systemctl enable xinetd
----
+
PXE 引导服务器现在已准备好为 PXE 客户机提供服务。您可以启动客户机(要安装 {productname} 的系统)，在提示指定引导源时选择 PXE Boot，然后开始网络安装。

[discrete]
== 其他资源

// To boot the client, see <XXX>
* 有关shim的更多信息，请参阅上游文档： link:https://www.rodsbooks.com/efi-bootloaders/secureboot.html#shim[使用shim程序]。
