[id='create-bootable-usb-linux_{context}']
= 在 Linux 上创建可引导 USB 设备

按照以下步骤在 Linux 系统上创建可引导 USB 设备。

[discrete]
== 前提

* 您已下载了安装 ISO 映像，如xref:standard-install:assembly_preparing-for-your-installation.adoc#downloading-beta-installation-images_preparing-for-your-installation[下载安装 ISO 映像]中所述。
* *DVD1* ISO 映像大于 4.7 GB，因此您必须有足够大的 USB 闪存驱动器来保存 ISO 映像。

[discrete]
== 步骤

[NOTE]
====
此过程具有破坏性，USB 闪存驱动器上的数据会在没有警告的情况下被销毁。
====

. 将 USB 闪存驱动器连接到系统。

. 打开终端窗口并运行 `dmesg` 命令：
+
[subs="quotes, macros, attributes"]
----
$ dmesg|tail
----
+
`dmesg` 命令返回一个详细记录所有最近事件的日志。日志底部显示连接的 USB 闪存驱动器产生的消息。记录所连接设备的名称。

. 切换到 root 用户：
+
[subs="quotes, macros, attributes"]
----
$ su -
----

. 出现提示时输入 root 密码。

. 查找分配给驱动器的设备节点。在本例中，驱动器名称为 `sdd`。
+
[subs="quotes, macros, attributes"]
----
# [command]#dmesg|tail#
[288954.686557] usb 2-1.8: New USB device strings: Mfr=0, Product=1, SerialNumber=2
[288954.686559] usb 2-1.8: Product: USB Storage
[288954.686562] usb 2-1.8: SerialNumber: 000000009225
[288954.712590] usb-storage 2-1.8:1.0: USB Mass Storage device detected
[288954.712687] scsi host6: usb-storage 2-1.8:1.0
[288954.712809] usbcore: registered new interface driver usb-storage
[288954.716682] usbcore: registered new interface driver uas
[288955.717140] scsi 6:0:0:0: Direct-Access     Generic  STORAGE DEVICE   9228 PQ: 0 ANSI: 0
[288955.717745] sd 6:0:0:0: Attached scsi generic sg4 type 0
[288961.876382] sd 6:0:0:0: *sdd* Attached SCSI removable disk
----

. 运行 `dd` 命令将 ISO 映像直接写入 USB 设备。
+
[subs="macros"]
----
# dd if=/image_directory/image.iso of=/dev/device
----
+
将 _/image_directory/image.iso_ 替换为您下载的 ISO 映像文件的完整路径，然后将 _device_ 替换为使用dmesg命令检索到的设备名称。在本例中，ISO 映像的完整路径为 `/home/testuser/Downloads/{ProductName}-{ProductNumber}-x86_64-boot.iso` ，设备名称为`sdd` ：
+
[subs="quotes, macros, attributes"]
----
# [command]#dd# if=/home/testuser/Downloads/{ProductName}-{ProductNumber}-x86_64-boot.iso of=/dev/sdd
----
+
[NOTE]
====
请确保使用正确的设备名称，而不是设备上分区的名称。分区名称通常是设备名后附加数字后缀。例如，`sdd` 是设备名称，`sdd1` 是设备 `sdd` 上的分区名称。
====

. 等待 `dd` 命令完成将映像写入设备的操作。出现 *#* 提示时，数据传输完成。显示提示时，请注销 root 帐户并拔下 USB 驱动器。现在可以将 USB 驱动器用作引导设备了。
