[id='booting-the-installer-from-local-media_{context}']
= 从 USB、CD 或 DVD 引导安装
//TODO: This isn't a procedure, came from alpha, needs to be changed.

按照以下步骤使用 USB、CD 或 DVD 引导 {productname} 安装。
以下步骤是通用的。有关具体说明，请参阅硬件制造商的文档。

.前提

您已经创建了可引导安装介质（USB、CD 或 DVD）。有关详细信息，请参阅xref:standard-install:assembly_preparing-for-your-installation.adoc#making-media_preparing-for-your-installation[创建安装介质]。


.步骤

. 关闭要安装 {productname} 系统的电源。

. 断开所有驱动器与系统的连接。

. 打开系统电源。

. 插入可引导安装介质（USB、DVD 或 CD）。

. 关闭系统电源，但不要取出引导介质。

. 打开系统电源。
+
[NOTE]
====
您可能需要按一个特定的键或组合键才能从介质引导，或者将系统的基本输入/输出系统（BIOS）配置为从介质引导。有关详细信息，请参阅系统随附的文档。
====

. *{rel8} 引导* 窗口打开并显示有关各种可用引导选项的信息。

. 使用键盘上的方向键选择所需的引导选项，然后按 *Enter* 键选择引导选项。*欢迎使用 {rel8}* 窗口打开，您可以使用图形用户界面安装 {productname}。
+
[NOTE]
====
如果在引导窗口中 60 秒内没有执行任何操作，安装程序将自动开始。
====

. 可选：对于基于 UEFI 的系统，按 *E* 编辑可用的引导选项。对于基于 BIOS 的系统，请按键盘上的 *Tab* 键编辑可用的引导选项。引导窗口进入编辑模式，您可以更改预定义的命令行以添加或删除引导选项。

.. 按 *Enter* 键确认您的选择。



.其他资源
* 有关使用图形用户界面安装 {productname} 的详细信息，请参阅xref:standard-install:assembly_graphical-installation.adoc[使用图形用户界面安装]。
* 有关可在引导命令行上使用的可用引导选项列表的更多信息，请参阅xref:standard-install:assembly_custom-boot-options.adoc[引导选项参考]。
