[id="booting-the-installation-using-pxe_{context}"]
= 使用 PXE 从网络引导安装

按照以下步骤使用 PXE 从网络引导 {productname} 安装。

[discrete]
== 前提

* 您已经配置了一个 TFTP 服务器，并且系统中有一个支持 PXE 的网络接口。有关更多信息，请参阅 *其他资源*。
* 您已将系统配置为从网络接口引导。该选项在 BIOS 中，并且可以标记为 *Network Boot* 或 *Boot Services*。
* 您已验证 BIOS 已配置为从指定的网络接口引导。一些 BIOS 系统将网络接口指定为可能的引导设备，但不支持 PXE 标准。有关更多信息，请参阅硬件文档。正确启用 PXE 引导后，系统可以在不使用任何其他介质的情况下引导 {rel8} 安装程序。

[discrete]
== 步骤

[NOTE]
====
要使用 PXE 从网络引导安装过程，必须使用物理网络连接，例如以太网。不能使用无线连接引导安装过程。
====

. 确认已连接网络电缆。即使计算机未打开，网络插座上的链接指示灯也应亮起。

. 打开系统。
+
根据硬件的不同，在系统连接到PXE服务器之前，可能会显示一些网络设置和诊断信息。连接后，将根据 PXE 服务器配置显示一个菜单。
+
. 按所需选项对应的数字键。
+
[NOTE]
====
在某些情况下，不显示启动选项。如果发生这种情况，请按键盘上的 *Enter* 键，或者等待直到引导窗口打开。
====
*{rel8} 引导* 窗口打开并显示有关各种可用引导选项的信息。
+
. 使用键盘上的方向键选择所需的引导选项，然后按 *Enter* 键选择引导选项。将打开 *欢迎使用 {rel8}* 窗口，您可以使用图形用户界面安装 {productname}。
+
[NOTE]
====
如果在引导窗口中 60 秒内没有执行任何操作，安装程序将自动开始。
====
+
. 可选：对于基于 UEFI 的系统，按 *E* 编辑可用的引导选项。对于基于 BIOS 的系统，请按键盘上的 *Tab* 键编辑可用的引导选项。引导窗口进入编辑模式，您可以更改预定义的命令行以添加或删除引导选项。

.. 按 *Enter* 键确认您的选择。

.其他资源

* 有关使用图形用户界面安装 {productname} 的详细信息，请参阅xref:standard-install:assembly_graphical-installation.adoc[使用图形用户界面安装]。
* 有关如何准备使用 PXE 从网络安装 {productname} 的信息，请参阅xref:advanced-install:index.adoc[_高级安装_]文档。
* 有关可在引导命令行上使用的可用引导选项列表的更多信息，请参阅xref:standard-install:assembly_custom-boot-options.adoc[引导选项参考]。
