[id="starting-a-kickstart-installation-automatically-using-pxe_{context}"]
= 使用 PXE 自动启动 Kickstart 安装


AMD64、Intel 64 和 64 位 ARM 系统能够使用 PXE 服务器引导。当您配置 PXE 服务器时，您可以将引导选项添加到引导加载程序配置文件中，从而允许您自动开始安装。使用此方法，可以完全自动化安装，包括引导过程。

此步骤仅作为一般参考；详细步骤因您的系统架构而异，并不是所有的选项在所有架构上都可用。


.前提

* 您必须在要安装的系统可访问的位置准备好 Kickstart 文件。
* 您必须具有可用于引导系统并开始安装的 PXE 服务器。

.步骤

. 打开 PXE 服务器上的引导加载程序配置文件，并将 [option]`inst.ks=` 引导选项添加到适当的行。文件的名称及其语法取决于系统的架构和硬件：
+
====
* 在带有 BIOS 的 AMD64 和 Intel 64 系统上，文件名可以是默认的，也可以基于系统的 IP 地址。在本例中，将 [option]`inst.ks=` 选项添加到安装条目中的 append 行。配置文件中的示例 append 行类似于以下内容：
+
----
append initrd=initrd.img inst.ks=http://10.32.5.1/mnt/archive/{ProductName}-8/8.x/x86_64/kickstarts/ks.cfg
----

* 在使用 GRUB2 引导加载程序的系统(带有 UEFI 固件的 AMD64、Intel 64 和 64 位 ARM 系统)上，文件名为 [filename]`grub.cfg`。在此文件中，将  [option]`inst.ks=` 选项追加到安装条目中的 kernel 行。配置文件中的示例 kernel 行如下所示：
+
----
kernel vmlinuz inst.ks=http://10.32.5.1/mnt/archive/{ProductName}-8/8.x/x86_64/kickstarts/ks.cfg
----
====

. 从网络服务器引导安装。
+
// For architecture-specific instructions, see: TODO XREFS !!!!
+
安装现在开始，使用 Kickstart 文件中指定的安装选项。如果 Kickstart 文件有效并且包含所有必需的命令，则安装完全自动化。

.其他资源

* 有关设置 PXE 服务器的信息，请参阅xref:assembly_preparing-for-a-network-install.adoc[使用 PXE 从网络准备安装]。
