[id="making-a-kickstart-file-available-on-an-ftp-server_{context}"]
= 使 Kickstart 文件在 FTP 服务器上可用

以下步骤介绍如何在 FTP 服务器上存储 Kickstart 脚本文件。您使用此方法可以从单个源安装多个系统，而不必为 Kickstart 文件使用物理介质。


.前提

* 您必须拥有对本地网络上安装了 {rel8} 的服务器的管理员级别访问权限。
* 要安装的系统必须能够连接到服务器。
* 服务器上的防火墙必须允许来自您要安装的系统的连接。有关更多信息，请参阅xref:assembly_making-kickstart-files-available-to-the-installation-program.adoc#ports-for-network-based-installation_making-kickstart-files-available-to-the-installation-program[基于网络安装的端口]。

.步骤

. 通过以 root 用户身份运行以下命令来安装 [package]`vsftpd` 软件包：
+
----
# yum install vsftpd
----

. 在文本编辑器中打开并编辑 [filename]`/etc/vsftpd/vsftpd.conf` 配置文件。

.. 将行 `anonymous_enable=NO` 更改为 `anonymous_enable=YES`

.. 将行 `write_enable=YES` 更改为 `write_enable=NO`.

.. 添加行 `pasv_min_port=__min_port__` 和 `pasv_max_port=__max_port__`。将 __min_port__ 和 __max_port__ 替换为被动模式下 FTP 服务器使用的端口号范围，例如 `10021` 和 `10031`。
+
在具有各种防火墙/NAT设置的网络环境中，此步骤可能是必要的。

.. （可选）将自定义更改添加到您的配置。有关可用选项，请参见 *vsftpd.conf(5)* 手册页。此步骤假定使用默认选项。
+
[WARNING]
====
如果在 [filename]`vsftpd.conf` 文件中配置了 SSL/TLS 安全性，请确保仅启用 TLSv1 协议，并禁用 SSLv2 和 SSLv3。这是由于 POODLE SSL 漏洞（CVE-2014-3566）。
====

. 配置服务器防火墙。

.. 启用防火墙：
+
----
# systemctl enable firewalld
# systemctl start firewalld
----

.. 在防火墙中启用上一步中的 FTP 端口和端口范围：
+
[subs="quotes"]
----
# firewall-cmd --add-port __min_port__-__max_port__/tcp --permanent
# firewall-cmd --add-service ftp --permanent
# firewall-cmd --reload
----
+
将 __min_port__-__max_port__ 替换为您在 [filename]`/etc/vsftpd/vsftpd.conf` 配置文件中输入的端口号。

. 将 Kickstart 文件复制到 FTP 服务器的 [filename]`/var/ftp/` 目录或其子目录中。

. 确保在文件上设置了正确的 SELinux 上下文和访问模式：
+
[subs="quotes"]
----
# restorecon -r /var/ftp/__your-kickstart-file.ks__
# chmod 444 /var/ftp/__your-kickstart-file.ks__
----

. 启动 `vsftpd` 服务：
+
----
# systemctl start vsftpd.service
----
+
如果在您更改 [filename]`/etc/vsftpd/vsftpd.conf` 文件之前该服务正在运行，请重新启动该服务以加载编辑后的文件：
+
----
# systemctl restart vsftpd.service
----
+
Kickstart 文件现在可以访问，可供同一网络上的系统进行安装。
+
[NOTE]
====
配置安装源时，请使用 `ftp://` 作为协议、服务器的主机名或 IP 地址以及 Kickstart 文件的路径(相对于 FTP 服务器根目录)。例如，如果服务器的主机名是 `myserver.example.com` ，并且您已将文件复制到 `/var/ftp/my-ks.cfg`，则将 `ftp://myserver.example.com/my-ks.cfg` 指定为安装源。
====
