[id="making-a-kickstart-file-available-on-an-http-or-https-server_{context}"]
= 使 Kickstart 文件在 HTTP 或 HTTPS 服务器上可用

以下步骤介绍如何在 HTTP 或 HTTPS 服务器上存储 Kickstart 脚本文件。您使用此方法可以从单个源安装多个系统，而不必为 Kickstart 文件使用物理介质。


.前提

* 您必须拥有对本地网络上安装了 {rel8} 的服务器的管理员级别访问权限。
* 要安装的系统必须能够连接到服务器。
* 服务器上的防火墙必须允许来自您要安装的系统的连接。有关更多信息，请参阅xref:assembly_making-kickstart-files-available-to-the-installation-program.adoc#ports-for-network-based-installation_making-kickstart-files-available-to-the-installation-program[基于网络安装的端口]。

.步骤

. 通过以 root 用户身份运行以下命令来安装 [package]`httpd` 软件包：
+
----
# yum install httpd
----
+
WARNING: 如果您的 Apache Web 服务器配置启用了 SSL 安全性，请验证您仅启用 TLSv1 协议，并禁用 SSLv2 和 SSLv3。这是由于 POODLE SSL漏洞（CVE-2014-3566）。
+
IMPORTANT: 如果将 HTTPS 服务器与自签名证书一起使用，则必须使用 [option]`inst.noverifyssl` 选项引导安装程序。

. 将 Kickstart 文件复制到 HTTP（S）服务器的 [filename]`/var/www/html/` 目录的子目录中。

. 启动 httpd 服务：
+
----
# systemctl start httpd.service
----
+
现在可以访问 Kickstart 文件，并可以将其用于安装了。
+
NOTE: 指定 Kickstart 文件的位置时，请使用 `http://` 或 `https://` 作为协议、服务器的主机名或 IP 地址以及 Kickstart 文件相对于 HTTP服务器根目录的路径。例如，如果您使用的是 HTTP，服务器的主机名是 `myserver.example.com`，并且您已经将Kickstart文件复制为 [filename]`/var/www/html/circle8-install/my-ks.cfg`，请指定 `http://myserver.example.com/circle8-install/my-ks.cfg` 作为文件位置。


