[id="recommended-partitioning-scheme_{context}"]
= 推荐的分区方案

{OrgName} 建议您在以下挂载点创建单独的文件系统：

* `/boot`

* `/` (root)

* `/home`

* `swap`

* `/boot/efi`



`/boot` 分区 —— 建议大小至少为 1 GiB::
+
挂载在 `/boot` 上的分区包含操作系统内核，它允许您的系统引导 {ProductName} {productnumber}，以及引导过程中使用的文件。由于大多数固件的限制，建议创建一个小分区来存放这些文件。在大多数情况下，1 GiB 引导分区就足够了。与其他挂载点不同，使用 LVM 卷作为`/boot` 是不可能的 —— `/boot` 必须位于单独的磁盘分区上。
+
WARNING: 通常，`/boot` 分区由安装程序自动创建。但是，如果`/` (root) 分区大于 2 TIB 并且使用 (U)EFI 引导，则需要创建一个小于 2 TiB 的单独/引导分区才能成功引导计算机。
+
NOTE: 如果您有 RAID 卡，请注意某些 BIOS 类型不支持从 RAID 卡引导。在这种情况下，必须在 RAID 阵列外部的分区上创建`/boot` 分区，例如在单独的硬盘上。

`root` - 建议大小为 10 GiB::
+
这是 "pass:attributes[{blank}]`/`pass:attributes[{blank}]" 或 root 目录所在的位置。root 目录是目录结构的顶层。默认情况下，所有文件都将写入此文件系统，除非要写入的路径中挂载了其他文件系统，例如 `/boot` 或 `/home`。
+
虽然 5 GiB 的根文件系统允许您安装最小安装，但建议您至少分配 10 GiB，以便您可以安装其他包组。
+
IMPORTANT: 不要将 `/` 目录与 `/root` 目录混淆。`/root` 目录是 root 用户的主目录。有时将 `/root` 目录称为 _斜杠 root_，以区别于 root 目录。

`/home` - 建议大小至少为 1 GiB::
+
要将用户数据与系统数据分开存储，请为 `/home` 目录创建专用文件系统。文件系统大小基于本地存储的数据量、用户数等。您可以升级或重新安装 {ProductName} {productnumber}，而不会擦除用户数据文件。如果选择自动分区，建议至少有 55 GiB 的磁盘空间可用于安装，以确保创建 `/home` 文件系统。

`swap` 分区 —— 建议大小至少为1 GiB::
+
交换文件系统支持虚拟内存；当没有足够的 RAM 来存储系统正在处理的数据时，数据将写入交换文件系统。交换大小是系统内存工作负载的函数，而不是系统总内存的函数，因此不等于系统总内存大小。重点分析系统将运行哪些应用程序以及这些应用程序将要承担的负载，以确定系统内存工作负载。应用程序提供商和开发人员可以提供指导。
+
当系统耗尽交换空间时，内核会在系统 RAM 内存耗尽时终止进程。配置过多的交换空间会导致存储设备被分配但处于空闲状态，并且不能很好地利用资源。过多的交换空间还可能隐藏内存泄漏。交换分区的最大大小和其他附加信息可以在 `mkswap(8)` 手册页中找到。
+
下表提供了交换分区的建议大小，具体取决于系统中的RAM容量以及是否要有足够的内存供系统休眠。如果您让安装程序自动对您的系统进行分区，则交换分区大小是根据以下准则确定的。自动分区设置假定未使用休眠。交换分区的最大大小限制为硬盘总大小的 10%，并且安装程序创建的交换分区大小不能超过 128 GB。要设置足够的交换空间以允许休眠，或者如果要将交换分区大小设置为系统存储空间的 10% 以上或 128 GB 以上，则必须手动编辑分区布局。

`/boot/efi` 分区 —— 建议大小为 200 MiB::

基于 UEFI 的 AMD64、Intel 64 和 64 位 ARM 需要 200 MiB EFI 系统分区。建议的最小大小为 200 MiB，默认大小为 600 MiB，最大大小为 600 MiB。
BIOS 系统不需要 EFI 系统分区。

.推荐的系统交换空间

[options="header"]
|===
|系统 RAM 容量|建议的交换空间|如果允许休眠，建议的交换空间
|小于 2 GB|RAM 容量的 2 倍|RAM 容量的 3 倍
|2 GB - 8 GB|等于 RAM 容量|RAM 容量的 2 倍
|8 GB - 64 GB|4 GB 到 RAM 容量的  倍|RAM 容量的 1.5
|大于 64 GB|取决于工作负载(至少  GB)|不建议休眠
|===

在每个范围之间的边界（例如，系统的 RAM 为8 GB 或64 GB），可以对选择的交换空间和休眠支持进行自由选择。如果您的系统资源允许的话，增加交换空间可以提高性能。

在多个存储设备上分配交换空间 —— 特别是在具有快速驱动器、控制器和接口的系统上 —— 也可以提高交换空间性能。

许多系统的分区和卷都超过了最低要求。根据您的特定系统需求选择分区。有关详细信息，请参阅 xref:standard-install:assembly_partitioning-reference.adoc#recommended-partitioning-scheme_partitioning-reference[建议的分区方案]。

[NOTE]
====
* 仅将存储容量分配给您立即需要的那些分区。您可以随时分配可用空间，以满足以后出现的需求。
* 如果不确定如何配置分区，请接受安装程序提供的自动默认分区布局。
====


// ...as described in installation-destination_graphical-installation.
// To learn about a more flexible method for storage management, see appe-lvm-overview.
