// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

// This module can be included from assemblies using the following include statement:
// include::<path>/ref_removed-boot-options.adoc[leveloffset=+1]

// The file name and the ID are based on the module title. For example:
// * file name: ref_my-reference-a.adoc
// * ID: [id='ref_my-reference-a_{context}']
// * Title: = My reference A
//
// The ID is used as an anchor for linking to the module. Avoid changing
// it after the module has been published to ensure existing links are not
// broken.
//
// The `context` attribute enables module reuse. Every module's ID includes
// {context}, which ensures that the module has a unique ID even if it is
// reused multiple times in a guide.
//
// In the title, include nouns that are used in the body text. This helps
// readers and search engines find information quickly.
[id="removed-boot-options_{context}"]
= 已删除的引导选项

本部分包含已从 {productname} 中删除的引导选项。

[NOTE]
====
`dracut` 提供高级引导选项。有关 `dracut` 的更多信息，请参见 `dracut.cmdline(7)` 手册页。
====

askmethod, asknetwork::
`initramfs` 是完全非交互式的，因此删除了 `askmethod` 和 `asknetwork` 选项。相反，可以使用 `inst.repo` 或指定适当的网络选项。

blacklist, nofirewire::
`modprobe` 选项处理列入黑名单的内核模块；使用 `modprobe.blacklist=<mod1>,<mod2>`。您可以使用 `modprobe.blacklist=firewire_ohci` 将 firewire 模块列入黑名单。

inst.headless=::
`headless=` 选项指定要安装的系统没有任何显示硬件，并且安装程序不需要查找任何显示硬件。

inst.decorated::
`inst.decorated` 选项用于指定装饰窗口中的图形安装。默认情况下，窗口没有装饰，因此它没有标题栏、调整大小等控件。不再需要此选项。

serial::
使用 `console=ttyS0` 选项。

updates::
使用 `inst.updates` 选项。

essid, wepkey, wpakey::
Dracut 不支持无线网络。

ethtool::
不再需要此选项。

gdb::
此选项已删除，因为有许多选项可用于调试基于 dracut 的 `initramfs`。

inst.mediacheck::
使用 `dracut option rd.live.check` 选项。

ks=floppy::
使用 `inst.ks=hd:<device>` 选项。

display::
要远程显示 UI，请使用 `inst.vnc` 选项。

utf8::
由于默认 TERM 设置的行为符合预期，因此不再需要此选项。

noipv6::
ipv6 内置于内核中，安装程序无法将其删除。您可以使用 `ipv6.disable=1` 禁用 IPv6。此设置由已安装的系统使用。

upgradeany::
安装程序不再处理升级，因此不再需要此选项。
