[id="commands-for-installing-rhel-8-content_{context}"]
= 安装 {rel8} 内容的命令

本部分列出安装  {rel8}  内容的常用命令。

.命令列表


安装软件包::
+
[subs="quotes"]
----
# yum install _package_
----
+
如果包是由模块流提供的，则 [command]`yum` 解析所需的模块流，并在安装此包时自动启用它。对于所有包依赖项，这种情况也是递归发生的。如果有更多的模块流满足要求，则使用默认的模块流。


使用其默认流启用模块::
+
[subs="quotes"]
----
# yum module enable __module-name__
----
+
当您希望使软件包对系统可用时启用模块，但此时不希望安装其中的任何一个。
//In prior versions of {ProductName}, this would be equivalent to adding a new yum repository but not actually installing any packages from it.
+
某些模块可能未定义默认流。在这种情况下，必须显式指定流。


使用特定流启用模块::
+
[subs="quotes"]
----
# yum module enable __module-name__:__stream__
----
+
如果模块定义了默认流，则可以省略流和冒号。


使用默认流和配置文件安装模块::
+
[subs="quotes"]
----
# yum install @__module-name__
----
+
或者：
+
[subs="quotes"]
----
# yum module install __module-name__
----
+
CAUTION: 有些模块没有定义默认流。


使用特定流和默认配置文件安装模块::
+
[subs="quotes"]
----
# yum install @__module-name__:__stream__
----
+
或者：
+
[subs="quotes"]
----
# yum module install __module-name__:__stream__
----
+
// CAUTION: It is theoretically possible that different streams might specify differently named profiles as default. This is not in Alpha, however.


使用特定流和配置文件安装模块::
+
[subs="quotes"]
----
# yum install @__module-name__:__stream__/__profile__
----
+
或者：
+
[subs="quotes"]
----
# yum module install __module-name__:__stream__/__profile__
----
+
// NOTE: This is the only fully defined/qualified variant of installation. Prefer this invocation in automation.
